// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: check_user_service.proto

package protoservices

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CheckUserServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
}

func (x *CheckUserServiceRequest) Reset() {
	*x = CheckUserServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_check_user_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserServiceRequest) ProtoMessage() {}

func (x *CheckUserServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_check_user_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserServiceRequest.ProtoReflect.Descriptor instead.
func (*CheckUserServiceRequest) Descriptor() ([]byte, []int) {
	return file_check_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUserServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type CheckUserServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CheckUserServiceResponse) Reset() {
	*x = CheckUserServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_check_user_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserServiceResponse) ProtoMessage() {}

func (x *CheckUserServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_check_user_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserServiceResponse.ProtoReflect.Descriptor instead.
func (*CheckUserServiceResponse) Descriptor() ([]byte, []int) {
	return file_check_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUserServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_check_user_service_proto protoreflect.FileDescriptor

var file_check_user_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x22, 0x3b, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a,
	0x18, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x8b, 0x01, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x77, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_check_user_service_proto_rawDescOnce sync.Once
	file_check_user_service_proto_rawDescData = file_check_user_service_proto_rawDesc
)

func file_check_user_service_proto_rawDescGZIP() []byte {
	file_check_user_service_proto_rawDescOnce.Do(func() {
		file_check_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_check_user_service_proto_rawDescData)
	})
	return file_check_user_service_proto_rawDescData
}

var file_check_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_check_user_service_proto_goTypes = []interface{}{
	(*CheckUserServiceRequest)(nil),  // 0: server.protoservices.CheckUserServiceRequest
	(*CheckUserServiceResponse)(nil), // 1: server.protoservices.CheckUserServiceResponse
}
var file_check_user_service_proto_depIdxs = []int32{
	0, // 0: server.protoservices.CheckUserService.CheckUserService:input_type -> server.protoservices.CheckUserServiceRequest
	1, // 1: server.protoservices.CheckUserService.CheckUserService:output_type -> server.protoservices.CheckUserServiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_check_user_service_proto_init() }
func file_check_user_service_proto_init() {
	if File_check_user_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_check_user_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUserServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_check_user_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUserServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_check_user_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_check_user_service_proto_goTypes,
		DependencyIndexes: file_check_user_service_proto_depIdxs,
		MessageInfos:      file_check_user_service_proto_msgTypes,
	}.Build()
	File_check_user_service_proto = out.File
	file_check_user_service_proto_rawDesc = nil
	file_check_user_service_proto_goTypes = nil
	file_check_user_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CheckUserServiceClient is the client API for CheckUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CheckUserServiceClient interface {
	CheckUserService(ctx context.Context, opts ...grpc.CallOption) (CheckUserService_CheckUserServiceClient, error)
}

type checkUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckUserServiceClient(cc grpc.ClientConnInterface) CheckUserServiceClient {
	return &checkUserServiceClient{cc}
}

func (c *checkUserServiceClient) CheckUserService(ctx context.Context, opts ...grpc.CallOption) (CheckUserService_CheckUserServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CheckUserService_serviceDesc.Streams[0], "/server.protoservices.CheckUserService/CheckUserService", opts...)
	if err != nil {
		return nil, err
	}
	x := &checkUserServiceCheckUserServiceClient{stream}
	return x, nil
}

type CheckUserService_CheckUserServiceClient interface {
	Send(*CheckUserServiceRequest) error
	Recv() (*CheckUserServiceResponse, error)
	grpc.ClientStream
}

type checkUserServiceCheckUserServiceClient struct {
	grpc.ClientStream
}

func (x *checkUserServiceCheckUserServiceClient) Send(m *CheckUserServiceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *checkUserServiceCheckUserServiceClient) Recv() (*CheckUserServiceResponse, error) {
	m := new(CheckUserServiceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CheckUserServiceServer is the server API for CheckUserService service.
type CheckUserServiceServer interface {
	CheckUserService(CheckUserService_CheckUserServiceServer) error
}

// UnimplementedCheckUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCheckUserServiceServer struct {
}

func (*UnimplementedCheckUserServiceServer) CheckUserService(CheckUserService_CheckUserServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method CheckUserService not implemented")
}

func RegisterCheckUserServiceServer(s *grpc.Server, srv CheckUserServiceServer) {
	s.RegisterService(&_CheckUserService_serviceDesc, srv)
}

func _CheckUserService_CheckUserService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CheckUserServiceServer).CheckUserService(&checkUserServiceCheckUserServiceServer{stream})
}

type CheckUserService_CheckUserServiceServer interface {
	Send(*CheckUserServiceResponse) error
	Recv() (*CheckUserServiceRequest, error)
	grpc.ServerStream
}

type checkUserServiceCheckUserServiceServer struct {
	grpc.ServerStream
}

func (x *checkUserServiceCheckUserServiceServer) Send(m *CheckUserServiceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *checkUserServiceCheckUserServiceServer) Recv() (*CheckUserServiceRequest, error) {
	m := new(CheckUserServiceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CheckUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.protoservices.CheckUserService",
	HandlerType: (*CheckUserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckUserService",
			Handler:       _CheckUserService_CheckUserService_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "check_user_service.proto",
}
