// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: get_available_service.proto

package protoservices

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetAavailableServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetAavailableServiceRequest) Reset() {
	*x = GetAavailableServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_available_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAavailableServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAavailableServiceRequest) ProtoMessage() {}

func (x *GetAavailableServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_available_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAavailableServiceRequest.ProtoReflect.Descriptor instead.
func (*GetAavailableServiceRequest) Descriptor() ([]byte, []int) {
	return file_get_available_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAavailableServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAavailableServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
}

func (x *GetAavailableServiceResponse) Reset() {
	*x = GetAavailableServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_available_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAavailableServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAavailableServiceResponse) ProtoMessage() {}

func (x *GetAavailableServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_available_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAavailableServiceResponse.ProtoReflect.Descriptor instead.
func (*GetAavailableServiceResponse) Descriptor() ([]byte, []int) {
	return file_get_available_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAavailableServiceResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

var File_get_available_service_proto protoreflect.FileDescriptor

var file_get_available_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x8f, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x41, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x77, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x31, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x32, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_get_available_service_proto_rawDescOnce sync.Once
	file_get_available_service_proto_rawDescData = file_get_available_service_proto_rawDesc
)

func file_get_available_service_proto_rawDescGZIP() []byte {
	file_get_available_service_proto_rawDescOnce.Do(func() {
		file_get_available_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_available_service_proto_rawDescData)
	})
	return file_get_available_service_proto_rawDescData
}

var file_get_available_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_available_service_proto_goTypes = []interface{}{
	(*GetAavailableServiceRequest)(nil),  // 0: server.protoservices.GetAavailableServiceRequest
	(*GetAavailableServiceResponse)(nil), // 1: server.protoservices.GetAavailableServiceResponse
}
var file_get_available_service_proto_depIdxs = []int32{
	0, // 0: server.protoservices.GetAavailableService.GetService:input_type -> server.protoservices.GetAavailableServiceRequest
	1, // 1: server.protoservices.GetAavailableService.GetService:output_type -> server.protoservices.GetAavailableServiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_get_available_service_proto_init() }
func file_get_available_service_proto_init() {
	if File_get_available_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_get_available_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAavailableServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_available_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAavailableServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_available_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_available_service_proto_goTypes,
		DependencyIndexes: file_get_available_service_proto_depIdxs,
		MessageInfos:      file_get_available_service_proto_msgTypes,
	}.Build()
	File_get_available_service_proto = out.File
	file_get_available_service_proto_rawDesc = nil
	file_get_available_service_proto_goTypes = nil
	file_get_available_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetAavailableServiceClient is the client API for GetAavailableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetAavailableServiceClient interface {
	GetService(ctx context.Context, in *GetAavailableServiceRequest, opts ...grpc.CallOption) (GetAavailableService_GetServiceClient, error)
}

type getAavailableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetAavailableServiceClient(cc grpc.ClientConnInterface) GetAavailableServiceClient {
	return &getAavailableServiceClient{cc}
}

func (c *getAavailableServiceClient) GetService(ctx context.Context, in *GetAavailableServiceRequest, opts ...grpc.CallOption) (GetAavailableService_GetServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GetAavailableService_serviceDesc.Streams[0], "/server.protoservices.GetAavailableService/GetService", opts...)
	if err != nil {
		return nil, err
	}
	x := &getAavailableServiceGetServiceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GetAavailableService_GetServiceClient interface {
	Recv() (*GetAavailableServiceResponse, error)
	grpc.ClientStream
}

type getAavailableServiceGetServiceClient struct {
	grpc.ClientStream
}

func (x *getAavailableServiceGetServiceClient) Recv() (*GetAavailableServiceResponse, error) {
	m := new(GetAavailableServiceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GetAavailableServiceServer is the server API for GetAavailableService service.
type GetAavailableServiceServer interface {
	GetService(*GetAavailableServiceRequest, GetAavailableService_GetServiceServer) error
}

// UnimplementedGetAavailableServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGetAavailableServiceServer struct {
}

func (*UnimplementedGetAavailableServiceServer) GetService(*GetAavailableServiceRequest, GetAavailableService_GetServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method GetService not implemented")
}

func RegisterGetAavailableServiceServer(s *grpc.Server, srv GetAavailableServiceServer) {
	s.RegisterService(&_GetAavailableService_serviceDesc, srv)
}

func _GetAavailableService_GetService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAavailableServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GetAavailableServiceServer).GetService(m, &getAavailableServiceGetServiceServer{stream})
}

type GetAavailableService_GetServiceServer interface {
	Send(*GetAavailableServiceResponse) error
	grpc.ServerStream
}

type getAavailableServiceGetServiceServer struct {
	grpc.ServerStream
}

func (x *getAavailableServiceGetServiceServer) Send(m *GetAavailableServiceResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GetAavailableService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.protoservices.GetAavailableService",
	HandlerType: (*GetAavailableServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetService",
			Handler:       _GetAavailableService_GetService_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "get_available_service.proto",
}
